---
- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repos
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Install docker packages
  apt:
    pkg:
    - python3-docker
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: Add the user 'vagrant' to group 'docker'
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Start docker service
  service:
    name: docker
    state: started
